<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-android;net9.0-ios</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>AppPreApha</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.AppPreApha</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>alexc</ApplicationPublisher>
    <!-- Package Description -->
    <Description>AppPreApha powered by Uno Platform.</Description>

    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Material;
      Dsp;
      Hosting;
      Toolkit;
      Authentication;
      ThemeService;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.Uno" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

</Project>
